image: node:latest

stages:
  - build
  - docker-build

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - echo "Start building App"
    - npm install
    - echo "Build successfully!"

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Built Docker Image Successfully!"